[network]
## Minimum transaction fee rate
min_relay_fee_rate=100000

## Network settings for p2p connections
ipv4=false
ipv6=false
listen=false
port=28456
tor=false
i2p=false

## Forward p2p port if listening
natpmp=false

## Maximum number of incoming connections
incoming_connections=0

## Maximum number of outgoing connections
outgoing_connections=0

## Database cache size
db_cache=132907008

## Do not create blocks larger than this limit
soft_block_size_limit=1000000

## Transaction memory pool size
tx_pool_size=132907008

## Include IP and other network addresses in debug output
log_endpoint=true

## SOCKS5 proxy for outgoing TCP/IP connections
# [network.proxy]
# host="127.0.0.1"
# port=9050

## I2P SAM application bridge
[network.i2p_sam]
host="127.0.0.1"
port=7656

## Tor proxy for onion connections
[network.tor_proxy]
host="127.0.0.1"
port=9050

## Tor control port
[network.tor_control]
host="127.0.0.1"
port=9051

## RPC server
[rpc]
enabled=true

[rpc.bind]
host="127.0.0.1"
port=8286
