#
# Copyright (c) 2026 Pavel Vasin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

[package]
name = "blacknet-json-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hashbrown = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true

[features]
default = []
client = []
server = ["dep:hashbrown"]

[lints]
workspace = true

[lib]
doctest = false
path = "src/main/rust/lib.rs"

[[test]]
name = "batch"
path = "src/test/rust/batch.rs"

[[test]]
name = "error"
path = "src/test/rust/error.rs"

[[test]]
name = "id"
path = "src/test/rust/id.rs"

[[test]]
name = "idgenerator"
path = "src/test/rust/idgenerator.rs"

[[test]]
name = "jsonrpc"
path = "src/test/rust/jsonrpc.rs"

[[test]]
name = "method"
path = "src/test/rust/method.rs"

[[test]]
name = "params"
path = "src/test/rust/params.rs"

[[test]]
name = "request"
path = "src/test/rust/request.rs"

[[test]]
name = "response"
path = "src/test/rust/response.rs"

[[test]]
name = "router"
path = "src/test/rust/router.rs"
